### ISSUE TITLE
A bit more documentation?

### ISSUE THREAD

**Issue by jornodberg** [hallyn/gtdtools#2]
Hi. Your project seems to be exactly what I need. I have been looking for something great on the commandline, which I also could keep in sync between multiple computers.

But I must say I'm a bit unsure as to how to use "Projects" the right way. The files "actions", "log" and "summary" - what should I put where?

I also wonder about the syntax in tickler repeating... Line start with "D" is for daynumber? "W" for weekly? "A" is for?

I know this is what you use yourself, and you don't owe me any explanation, but I still hope you will provide me with more info, as I think I could end up using this for a long time.

Greetings from Norway.

**Comment by hallyn** [comment]
Sorry, you're right.  I should do this.  I'm making a note to do so.

**Comment by hallyn** [comment]
Still need to add some stuff about project completion etc.  And the README could be made much nicer to read.  But I've added some more info now about how to use some of these files.
